// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB98QcxpbiNfLrGDeLMiG972QJ7daoJ45w',
    appId: '1:792091963600:web:2b46abd9dcb0f2c1f42ed5',
    messagingSenderId: '792091963600',
    projectId: 'pomodoro-53e3e',
    authDomain: 'pomodoro-53e3e.firebaseapp.com',
    databaseURL: 'https://pomodoro-53e3e-default-rtdb.firebaseio.com',
    storageBucket: 'pomodoro-53e3e.firebasestorage.app',
    measurementId: 'G-LQZX92L95C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLu2JeIx9RGndolKv0RH0bBlAi81v97PQ',
    appId: '1:792091963600:android:e55780845de273e1f42ed5',
    messagingSenderId: '792091963600',
    projectId: 'pomodoro-53e3e',
    databaseURL: 'https://pomodoro-53e3e-default-rtdb.firebaseio.com',
    storageBucket: 'pomodoro-53e3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGp7Qz4SWCdXdhfNaBpb8rBVkzuaxOgs',
    appId: '1:792091963600:ios:5b143f88e7860348f42ed5',
    messagingSenderId: '792091963600',
    projectId: 'pomodoro-53e3e',
    databaseURL: 'https://pomodoro-53e3e-default-rtdb.firebaseio.com',
    storageBucket: 'pomodoro-53e3e.firebasestorage.app',
    iosBundleId: 'com.grullondev.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGp7Qz4SWCdXdhfNaBpb8rBVkzuaxOgs',
    appId: '1:792091963600:ios:38f9bfd777406febf42ed5',
    messagingSenderId: '792091963600',
    projectId: 'pomodoro-53e3e',
    databaseURL: 'https://pomodoro-53e3e-default-rtdb.firebaseio.com',
    storageBucket: 'pomodoro-53e3e.firebasestorage.app',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB98QcxpbiNfLrGDeLMiG972QJ7daoJ45w',
    appId: '1:792091963600:web:5b6ff46a1b4847adf42ed5',
    messagingSenderId: '792091963600',
    projectId: 'pomodoro-53e3e',
    authDomain: 'pomodoro-53e3e.firebaseapp.com',
    databaseURL: 'https://pomodoro-53e3e-default-rtdb.firebaseio.com',
    storageBucket: 'pomodoro-53e3e.firebasestorage.app',
    measurementId: 'G-SFMBY5R0R0',
  );
}
